server:
  port: 8091

spring:
  application:
    name: shop-service
  datasource:
    url: jdbc:mysql://localhost:3306/eshop
    username: root
    password: 654321
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true